// Auto-generated weekly suburb batches
// Total new: 207

export const WEEKLY_BATCHES = [
  // Batch 1 (42 suburbs)
  ["Aberfeldie", "VIC", ""],
  ["Airport West", "VIC", ""],
  ["Altona Meadows", "VIC", ""],
  ["Altona North", "VIC", ""],
  ["Armstrong Creek", "VIC", ""],
  ["Ashburton", "VIC", ""],
  ["Ashwood", "VIC", ""],
  ["Aspendale", "VIC", ""],
  ["Ballarat", "VIC", ""],
  ["Balwyn North", "VIC", "3104"],
  ["Bayswater", "VIC", ""],
  ["Bayswater North", "VIC", ""],
  ["Beaconsfield", "VIC", ""],
  ["Beaconsfield Upper", "VIC", ""],
  ["Beaumaris", "VIC", ""],
  ["Bell Park", "VIC", ""],
  ["Bell Post Hill", "VIC", ""],
  ["Belmont", "VIC", ""],
  ["Bendigo", "VIC", ""],
  ["Bentleigh", "VIC", ""],
  ["Bentleigh East", "VIC", ""],
  ["Bentleigh East", "VIC", "3165"],
  ["Berwick", "VIC", ""],
  ["Black Rock", "VIC", ""],
  ["Blackburn", "VIC", ""],
  ["Blackburn", "VIC", "3130"],
  ["Blackburn North", "VIC", ""],
  ["Blackburn South", "VIC", ""],
  ["Blairgowrie", "VIC", ""],
  ["Bonbeach", "VIC", ""],
  ["Boronia", "VIC", ""],
  ["Botanic Ridge", "VIC", ""],
  ["Braybrook", "VIC", ""],
  ["Brighton", "VIC", ""],
  ["Brighton East", "VIC", ""],
  ["Broadmeadows", "VIC", ""],
  ["Brunswick West", "VIC", ""],
  ["Bundoora", "VIC", ""],
  ["Burwood", "VIC", ""],
  ["Burwood East", "VIC", ""],
  ["Cairnlea", "VIC", ""],
  ["Carnegie", "VIC", ""],

  // Batch 2 (42 suburbs)
  ["Carnegie", "VIC", "3163"],
  ["Caroline Springs", "VIC", ""],
  ["Carrum Downs", "VIC", ""],
  ["Caulfield", "VIC", ""],
  ["Caulfield East", "VIC", ""],
  ["Chadstone", "VIC", ""],
  ["Chelsea", "VIC", ""],
  ["Cheltenham", "VIC", ""],
  ["Chirnside Park", "VIC", ""],
  ["Clarinda", "VIC", ""],
  ["Clayton", "VIC", ""],
  ["Clayton", "VIC", "3168"],
  ["Clayton South", "VIC", ""],
  ["Clayton South", "VIC", "3169"],
  ["Clyde", "VIC", ""],
  ["Clyde North", "VIC", ""],
  ["Coburg North", "VIC", ""],
  ["Craigieburn", "VIC", ""],
  ["Cranbourne", "VIC", ""],
  ["Cranbourne East", "VIC", ""],
  ["Croydon", "VIC", ""],
  ["Croydon North", "VIC", ""],
  ["Croydon South", "VIC", ""],
  ["Dandenong", "VIC", ""],
  ["Deer Park", "VIC", ""],
  ["Derrimut", "VIC", ""],
  ["Diggers Rest", "VIC", ""],
  ["Dingley Village", "VIC", ""],
  ["Doncaster East", "VIC", ""],
  ["Doncaster East", "VIC", "3109"],
  ["Donnybrook", "VIC", ""],
  ["Donvale", "VIC", ""],
  ["Dromana", "VIC", ""],
  ["Eaglemont", "VIC", ""],
  ["Edithvale", "VIC", ""],
  ["Elsternwick", "VIC", ""],
  ["Endeavour Hills", "VIC", ""],
  ["Epping", "VIC", ""],
  ["Fairfield", "VIC", ""],
  ["Fawkner", "VIC", ""],
  ["Ferntree Gully", "VIC", ""],
  ["Forest Hill", "VIC", ""],

  // Batch 3 (42 suburbs)
  ["Frankston", "VIC", ""],
  ["Frankston South", "VIC", ""],
  ["Glen Huntly", "VIC", ""],
  ["Glen Waverley", "VIC", ""],
  ["Glen Waverley", "VIC", "3150"],
  ["Gowanbrae", "VIC", ""],
  ["Greenvale", "VIC", ""],
  ["Hallam", "VIC", ""],
  ["Hampton", "VIC", ""],
  ["Hampton Park", "VIC", ""],
  ["Hastings", "VIC", ""],
  ["Hawthorn East", "VIC", ""],
  ["Heatherton", "VIC", ""],
  ["Heathmont", "VIC", ""],
  ["Heidelberg Heights", "VIC", ""],
  ["Highett", "VIC", ""],
  ["Highton", "VIC", ""],
  ["Hoppers Crossing", "VIC", ""],
  ["Hughesdale", "VIC", ""],
  ["Huntingdale", "VIC", ""],
  ["Ivanhoe East", "VIC", ""],
  ["Keilor Park", "VIC", ""],
  ["Keysborough", "VIC", ""],
  ["Kilsyth", "VIC", ""],
  ["Knoxfield", "VIC", ""],
  ["Lalor", "VIC", ""],
  ["Langwarrin", "VIC", ""],
  ["Langwarrin South", "VIC", ""],
  ["Lara", "VIC", ""],
  ["Laverton", "VIC", ""],
  ["Leopold", "VIC", ""],
  ["Lilydale", "VIC", ""],
  ["Lynbrook", "VIC", ""],
  ["Lyndhurst", "VIC", ""],
  ["Lysterfield", "VIC", ""],
  ["Macleod", "VIC", ""],
  ["Maidstone", "VIC", ""],
  ["Malvern East", "VIC", ""],
  ["Malvern East", "VIC", "3145"],
  ["Manor Lakes", "VIC", ""],
  ["Maribyrnong", "VIC", ""],
  ["McCrae", "VIC", ""],

  // Batch 4 (42 suburbs)
  ["McKinnon", "VIC", ""],
  ["Melton", "VIC", ""],
  ["Mentone", "VIC", ""],
  ["Mernda", "VIC", ""],
  ["Mickleham", "VIC", ""],
  ["Mitcham", "VIC", ""],
  ["Mont Albert", "VIC", ""],
  ["Moorabbin", "VIC", ""],
  ["Mooroolbark", "VIC", ""],
  ["Mordialloc", "VIC", ""],
  ["Mornington", "VIC", ""],
  ["Mount Eliza", "VIC", ""],
  ["Mount Martha", "VIC", ""],
  ["Mount Waverley", "VIC", ""],
  ["Mount Waverley", "VIC", "3149"],
  ["Mulgrave", "VIC", ""],
  ["Murrumbeena", "VIC", ""],
  ["Narre Warren", "VIC", ""],
  ["Narre Warren East", "VIC", ""],
  ["Narre Warren North", "VIC", ""],
  ["Narre Warren South", "VIC", ""],
  ["Newtown", "VIC", ""],
  ["Noble Park", "VIC", ""],
  ["Notting Hill", "VIC", ""],
  ["Nunawading", "VIC", ""],
  ["Oakleigh", "VIC", ""],
  ["Oakleigh", "VIC", "3166"],
  ["Oakleigh East", "VIC", ""],
  ["Oakleigh South", "VIC", ""],
  ["Oakleigh South", "VIC", "3167"],
  ["Ocean Grove", "VIC", ""],
  ["Officer", "VIC", ""],
  ["Officer South", "VIC", ""],
  ["Ormond", "VIC", ""],
  ["Pakenham", "VIC", ""],
  ["Parkdale", "VIC", ""],
  ["Pascoe Vale South", "VIC", ""],
  ["Patterson Lakes", "VIC", ""],
  ["Reservoir", "VIC", ""],
  ["Ringwood", "VIC", ""],
  ["Ringwood East", "VIC", ""],
  ["Rockbank", "VIC", ""],

  // Batch 5 (39 suburbs)
  ["Rosanna", "VIC", ""],
  ["Rosebud", "VIC", ""],
  ["Rowville", "VIC", ""],
  ["Rye", "VIC", ""],
  ["Safety Beach", "VIC", ""],
  ["Sandringham", "VIC", ""],
  ["Scoresby", "VIC", "3179"],
  ["Seaford", "VIC", ""],
  ["Skye", "VIC", ""],
  ["Somerville", "VIC", ""],
  ["South Morang", "VIC", ""],
  ["South Yarra", "VIC", ""],
  ["Springvale", "VIC", ""],
  ["St Albans", "VIC", ""],
  ["Strathmore", "VIC", ""],
  ["Sunbury", "VIC", ""],
  ["Sunshine", "VIC", ""],
  ["Sunshine North", "VIC", ""],
  ["Sunshine West", "VIC", ""],
  ["Tarneit", "VIC", ""],
  ["Templestowe", "VIC", ""],
  ["Thomastown", "VIC", ""],
  ["Tootgarook", "VIC", ""],
  ["Torquay", "VIC", ""],
  ["Truganina", "VIC", ""],
  ["Vermont", "VIC", ""],
  ["Vermont South", "VIC", ""],
  ["Vermont South", "VIC", "3133"],
  ["Viewbank", "VIC", ""],
  ["Wantirna", "VIC", ""],
  ["Wantirna South", "VIC", ""],
  ["Warranwood", "VIC", ""],
  ["Watsonia", "VIC", ""],
  ["Waurn Ponds", "VIC", ""],
  ["Werribee South", "VIC", ""],
  ["West Footscray", "VIC", ""],
  ["Wheelers Hill", "VIC", ""],
  ["Wollert", "VIC", ""],
  ["Wyndham Vale", "VIC", ""],

];
