// Auto-generated from user rank ordering
// 230 suburbs in 5 batches (~46 each)

export const WEEKLY_BATCHES = [
  // Batch 1
  [
    ["Canterbury", "VIC", ""],
    ["Toorak", "VIC", "3142"],
    ["Balwyn", "VIC", ""],
    ["Balwyn North", "VIC", "3104"],
    ["Brighton", "VIC", ""],
    ["Hawthorn", "VIC", "3122"],
    ["Kew", "VIC", "3101"],
    ["Camberwell", "VIC", "3124"],
    ["Brighton East", "VIC", ""],
    ["Hawthorn East", "VIC", ""],
    ["Malvern", "VIC", ""],
    ["Beaumaris", "VIC", ""],
    ["Black Rock", "VIC", ""],
    ["Middle Park", "VIC", ""],
    ["Albert Park", "VIC", ""],
    ["Ivanhoe East", "VIC", ""],
    ["Eaglemont", "VIC", ""],
    ["Mount Waverley", "VIC", "3149"],
    ["McKinnon", "VIC", ""],
    ["Doncaster East", "VIC", "3109"],
    ["Wheelers Hill", "VIC", ""],
    ["Surrey Hills", "VIC", ""],
    ["Sandringham", "VIC", ""],
    ["Parkdale", "VIC", ""],
    ["Mentone", "VIC", ""],
    ["Templestowe", "VIC", ""],
    ["Oakleigh South", "VIC", "3167"],
    ["Bentleigh", "VIC", ""],
    ["Bentleigh East", "VIC", "3165"],
    ["Hampton", "VIC", ""],
    ["Mordialloc", "VIC", ""],
    ["Blackburn", "VIC", "3130"],
    ["Vermont South", "VIC", "3133"],
    ["Williamstown", "VIC", ""],
    ["Ashburton", "VIC", ""],
    ["Caulfield North", "VIC", ""],
    ["Caulfield South", "VIC", ""],
    ["Malvern East", "VIC", "3145"],
    ["Rosanna", "VIC", ""],
    ["Ivanhoe", "VIC", ""],
    ["Donvale", "VIC", ""],
    ["Blackburn South", "VIC", ""],
    ["Murrumbeena", "VIC", ""],
    ["Cheltenham", "VIC", ""],
    ["Highett", "VIC", ""],
    ["Heidelberg", "VIC", ""],
  ],
  // Batch 2
  [
    ["Elwood", "VIC", ""],
    ["Elsternwick", "VIC", ""],
    ["Carnegie", "VIC", "3163"],
    ["Oakleigh", "VIC", "3166"],
    ["Blackburn North", "VIC", ""],
    ["Burwood", "VIC", ""],
    ["Burwood East", "VIC", ""],
    ["Moorabbin", "VIC", ""],
    ["Ashwood", "VIC", ""],
    ["Forest Hill", "VIC", ""],
    ["Ringwood East", "VIC", ""],
    ["Ringwood", "VIC", ""],
    ["Heathmont", "VIC", ""],
    ["Strathmore", "VIC", ""],
    ["Essendon", "VIC", ""],
    ["Pascoe Vale South", "VIC", ""],
    ["Pascoe Vale", "VIC", ""],
    ["Aberfeldie", "VIC", ""],
    ["Maribyrnong", "VIC", ""],
    ["Yarraville", "VIC", ""],
    ["Northcote", "VIC", ""],
    ["Fairfield", "VIC", ""],
    ["Thornbury", "VIC", ""],
    ["Brunswick West", "VIC", ""],
    ["Brunswick", "VIC", ""],
    ["South Yarra", "VIC", ""],
    ["Port Melbourne", "VIC", ""],
    ["West Melbourne", "VIC", ""],
    ["Coburg", "VIC", ""],
    ["Coburg North", "VIC", ""],
    ["Preston", "VIC", ""],
    ["Macleod", "VIC", ""],
    ["Viewbank", "VIC", ""],
    ["Watsonia", "VIC", ""],
    ["Nunawading", "VIC", ""],
    ["Mitcham", "VIC", ""],
    ["Wantirna South", "VIC", ""],
    ["Wantirna", "VIC", ""],
    ["Scoresby", "VIC", "3179"],
    ["Rowville", "VIC", ""],
    ["Lysterfield", "VIC", ""],
    ["Dingley Village", "VIC", ""],
    ["Clarinda", "VIC", ""],
    ["Clayton", "VIC", "3168"],
    ["Hughesdale", "VIC", ""],
    ["Glen Huntly", "VIC", ""],
  ],
  // Batch 3
  [
    ["Caulfield", "VIC", ""],
    ["Caulfield East", "VIC", ""],
    ["Chadstone", "VIC", ""],
    ["Box Hill", "VIC", "3128"],
    ["Heatherton", "VIC", ""],
    ["Oakleigh East", "VIC", ""],
    ["Mooroolbark", "VIC", ""],
    ["Lilydale", "VIC", ""],
    ["Croydon North", "VIC", ""],
    ["Croydon South", "VIC", ""],
    ["Croydon", "VIC", ""],
    ["Warranwood", "VIC", ""],
    ["Beaconsfield Upper", "VIC", ""],
    ["Beaconsfield", "VIC", ""],
    ["Berwick", "VIC", ""],
    ["Narre Warren North", "VIC", ""],
    ["Frankston South", "VIC", ""],
    ["Mount Eliza", "VIC", ""],
    ["Mornington", "VIC", ""],
    ["Safety Beach", "VIC", ""],
    ["Dromana", "VIC", ""],
    ["Mount Martha", "VIC", ""],
    ["Ocean Grove", "VIC", ""],
    ["Torquay", "VIC", ""],
    ["Newtown", "VIC", ""],
    ["Highton", "VIC", ""],
    ["Waurn Ponds", "VIC", ""],
    ["Belmont", "VIC", ""],
    ["Leopold", "VIC", ""],
    ["Lara", "VIC", ""],
    ["Ballarat", "VIC", ""],
    ["Bendigo", "VIC", ""],
    ["Langwarrin South", "VIC", ""],
    ["Langwarrin", "VIC", ""],
    ["Edithvale", "VIC", ""],
    ["Aspendale", "VIC", ""],
    ["Bonbeach", "VIC", ""],
    ["Chelsea", "VIC", ""],
    ["Patterson Lakes", "VIC", ""],
    ["Seaford", "VIC", ""],
    ["Frankston", "VIC", ""],
    ["Narre Warren East", "VIC", ""],
    ["Narre Warren", "VIC", ""],
    ["Narre Warren South", "VIC", ""],
    ["Lynbrook", "VIC", ""],
    ["Lyndhurst", "VIC", ""],
  ],
  // Batch 4
  [
    ["Keysborough", "VIC", ""],
    ["Springvale", "VIC", ""],
    ["Clayton South", "VIC", "3169"],
    ["Huntingdale", "VIC", ""],
    ["Glenroy", "VIC", ""],
    ["Gowanbrae", "VIC", ""],
    ["Greenvale", "VIC", ""],
    ["Airport West", "VIC", ""],
    ["Keilor Park", "VIC", ""],
    ["Bundoora", "VIC", ""],
    ["Heidelberg Heights", "VIC", ""],
    ["Altona", "VIC", ""],
    ["Altona North", "VIC", ""],
    ["Altona Meadows", "VIC", ""],
    ["Cairnlea", "VIC", ""],
    ["Caroline Springs", "VIC", ""],
    ["Deer Park", "VIC", ""],
    ["Sunshine West", "VIC", ""],
    ["Sunshine North", "VIC", ""],
    ["Sunshine", "VIC", ""],
    ["West Footscray", "VIC", ""],
    ["Maidstone", "VIC", ""],
    ["Footscray", "VIC", ""],
    ["Braybrook", "VIC", ""],
    ["St Albans", "VIC", ""],
    ["Fawkner", "VIC", ""],
    ["Lalor", "VIC", ""],
    ["Thomastown", "VIC", ""],
    ["Reservoir", "VIC", ""],
    ["Epping", "VIC", ""],
    ["South Morang", "VIC", ""],
    ["Mernda", "VIC", ""],
    ["Wollert", "VIC", ""],
    ["Craigieburn", "VIC", ""],
    ["Mickleham", "VIC", ""],
    ["Donnybrook", "VIC", ""],
    ["Sunbury", "VIC", ""],
    ["Diggers Rest", "VIC", ""],
    ["Rockbank", "VIC", ""],
    ["Truganina", "VIC", ""],
    ["Tarneit", "VIC", ""],
    ["Wyndham Vale", "VIC", ""],
    ["Werribee", "VIC", ""],
    ["Point Cook", "VIC", ""],
    ["Werribee South", "VIC", ""],
    ["Manor Lakes", "VIC", ""],
  ],
  // Batch 5
  [
    ["Hoppers Crossing", "VIC", ""],
    ["Laverton", "VIC", ""],
    ["Derrimut", "VIC", ""],
    ["Skye", "VIC", ""],
    ["Somerville", "VIC", ""],
    ["Hastings", "VIC", ""],
    ["Botanic Ridge", "VIC", ""],
    ["Clyde North", "VIC", ""],
    ["Clyde", "VIC", ""],
    ["Officer South", "VIC", ""],
    ["Officer", "VIC", ""],
    ["Pakenham", "VIC", ""],
    ["Armstrong Creek", "VIC", ""],
    ["Carrum Downs", "VIC", ""],
    ["Hallam", "VIC", ""],
    ["Hampton Park", "VIC", ""],
    ["Cranbourne East", "VIC", ""],
    ["Cranbourne", "VIC", ""],
    ["Bell Park", "VIC", ""],
    ["Bell Post Hill", "VIC", ""],
    ["Kilsyth", "VIC", ""],
    ["Knoxfield", "VIC", ""],
    ["Ferntree Gully", "VIC", ""],
    ["Boronia", "VIC", ""],
    ["Bayswater North", "VIC", ""],
    ["Bayswater", "VIC", ""],
    ["Chirnside Park", "VIC", ""],
    ["Tootgarook", "VIC", ""],
    ["Rosebud", "VIC", ""],
    ["Rye", "VIC", ""],
    ["Blairgowrie", "VIC", ""],
    ["McCrae", "VIC", ""],
    ["Notting Hill", "VIC", ""],
    ["Noble Park", "VIC", ""],
    ["Dandenong", "VIC", ""],
    ["Melton", "VIC", ""],
    ["Broadmeadows", "VIC", ""],
    ["Endeavour Hills", "VIC", ""],
    ["Glen Waverley", "VIC", "3150"],
    ["Mulgrave", "VIC", ""],
    ["Mont Albert", "VIC", ""],
    ["Ormond", "VIC", ""],
    ["Vermont", "VIC", ""],
    ["Doncaster", "VIC", "3108"],
    ["North Melbourne", "VIC", ""],
    ["Newport", "VIC", ""],
  ],
];
