-- ============================================================================
-- Migration 013: Investor Watch Phase 1 foundation
--
-- Creates member authentication, membership, watchlist and report-usage tables.
-- This migration does not create subscriptions, send email, call Stripe, or
-- modify existing customer/report tables.
--
-- Dependencies:
--   migration-009-customer-funnel.sql (lead_contacts)
--   migration-010-report-payments.sql (report_snapshots)
-- ============================================================================

BEGIN;

-- A. One-time Magic Link tokens. Only a SHA-256 hash is stored.
CREATE TABLE IF NOT EXISTS member_login_tokens (
    id                          BIGSERIAL PRIMARY KEY,
    lead_contact_id             BIGINT NOT NULL REFERENCES lead_contacts(id) ON DELETE CASCADE,
    token_hash                  TEXT NOT NULL UNIQUE,
    requested_ip_hash           TEXT,
    requested_user_agent_hash   TEXT,
    expires_at                  TIMESTAMPTZ NOT NULL,
    consumed_at                 TIMESTAMPTZ,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_member_login_token_expiry
        CHECK (expires_at > created_at),
    CONSTRAINT chk_member_login_token_consumed
        CHECK (consumed_at IS NULL OR consumed_at >= created_at)
);

CREATE INDEX IF NOT EXISTS idx_member_login_tokens_contact
    ON member_login_tokens (lead_contact_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_member_login_tokens_expires
    ON member_login_tokens (expires_at)
    WHERE consumed_at IS NULL;

-- B. Revocable long-lived member sessions. Raw session tokens are never stored.
CREATE TABLE IF NOT EXISTS member_sessions (
    id                  BIGSERIAL PRIMARY KEY,
    lead_contact_id     BIGINT NOT NULL REFERENCES lead_contacts(id) ON DELETE CASCADE,
    session_token_hash  TEXT NOT NULL UNIQUE,
    expires_at          TIMESTAMPTZ NOT NULL,
    last_seen_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    revoked_at          TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_member_session_expiry
        CHECK (expires_at > created_at),
    CONSTRAINT chk_member_session_revoked
        CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE INDEX IF NOT EXISTS idx_member_sessions_contact_expiry
    ON member_sessions (lead_contact_id, expires_at DESC);
CREATE INDEX IF NOT EXISTS idx_member_sessions_active_expiry
    ON member_sessions (expires_at)
    WHERE revoked_at IS NULL;

-- C. One membership record per known contact.
CREATE TABLE IF NOT EXISTS investor_watch_memberships (
    id                      BIGSERIAL PRIMARY KEY,
    lead_contact_id         BIGINT NOT NULL UNIQUE REFERENCES lead_contacts(id) ON DELETE CASCADE,
    status                  TEXT NOT NULL DEFAULT 'preview',
    stripe_customer_id      TEXT UNIQUE,
    stripe_subscription_id  TEXT UNIQUE,
    current_period_start    TIMESTAMPTZ,
    current_period_end      TIMESTAMPTZ,
    cancel_at_period_end    BOOLEAN NOT NULL DEFAULT FALSE,
    report_limit            INTEGER NOT NULL DEFAULT 10,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_investor_watch_membership_status CHECK (
        status IN ('preview', 'trialing', 'active', 'past_due', 'canceled', 'unpaid')
    ),
    CONSTRAINT chk_investor_watch_report_limit
        CHECK (report_limit >= 0 AND report_limit <= 100),
    CONSTRAINT chk_investor_watch_period CHECK (
        current_period_start IS NULL
        OR current_period_end IS NULL
        OR current_period_end > current_period_start
    )
);

CREATE INDEX IF NOT EXISTS idx_investor_watch_memberships_status
    ON investor_watch_memberships (status);
CREATE INDEX IF NOT EXISTS idx_investor_watch_memberships_period_end
    ON investor_watch_memberships (current_period_end)
    WHERE status IN ('trialing', 'active', 'past_due');

-- D. Saved suburbs and properties. canonical_item_key is generated by the
-- service; it must never be trusted from a client request.
CREATE TABLE IF NOT EXISTS investor_watch_items (
    id                  BIGSERIAL PRIMARY KEY,
    lead_contact_id     BIGINT NOT NULL REFERENCES lead_contacts(id) ON DELETE CASCADE,
    item_type           TEXT NOT NULL,
    canonical_item_key  TEXT NOT NULL,
    suburb              TEXT NOT NULL,
    state               TEXT NOT NULL,
    postcode            TEXT,
    property_key        TEXT,
    display_address     TEXT,
    investment_goal     TEXT,
    private_note        TEXT,
    status              TEXT NOT NULL DEFAULT 'active',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_investor_watch_item_type
        CHECK (item_type IN ('suburb', 'property')),
    CONSTRAINT chk_investor_watch_item_status
        CHECK (status IN ('active', 'archived')),
    CONSTRAINT chk_investor_watch_item_identity CHECK (
        (item_type = 'suburb' AND property_key IS NULL)
        OR
        (item_type = 'property' AND property_key IS NOT NULL)
    ),
    CONSTRAINT chk_investor_watch_goal CHECK (
        investment_goal IS NULL
        OR investment_goal IN ('balanced', 'growth', 'income', 'school', 'value')
    ),
    CONSTRAINT chk_investor_watch_note_length
        CHECK (private_note IS NULL OR char_length(private_note) <= 1000),
    CONSTRAINT chk_investor_watch_state_length
        CHECK (char_length(state) BETWEEN 2 AND 3),
    CONSTRAINT chk_investor_watch_canonical_key
        CHECK (char_length(canonical_item_key) BETWEEN 3 AND 500)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_investor_watch_items_active_unique
    ON investor_watch_items (lead_contact_id, canonical_item_key)
    WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_investor_watch_items_contact_status
    ON investor_watch_items (lead_contact_id, status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_investor_watch_items_suburb_state
    ON investor_watch_items (suburb, state)
    WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_investor_watch_items_property_key
    ON investor_watch_items (property_key)
    WHERE item_type = 'property' AND status = 'active';

-- E. Idempotent membership report allowance ledger. A report can consume an
-- allowance only once for a membership, even across later billing periods.
CREATE TABLE IF NOT EXISTS membership_report_usage (
    id                    BIGSERIAL PRIMARY KEY,
    membership_id         BIGINT NOT NULL REFERENCES investor_watch_memberships(id) ON DELETE CASCADE,
    report_id             TEXT NOT NULL REFERENCES report_snapshots(report_id),
    property_key          TEXT NOT NULL,
    billing_period_start  TIMESTAMPTZ NOT NULL,
    usage_type            TEXT NOT NULL,
    idempotency_key       TEXT NOT NULL UNIQUE,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_membership_report_usage_type CHECK (
        usage_type IN ('included_report', 'trial_report', 'adjustment')
    ),
    CONSTRAINT uq_membership_report_once UNIQUE (membership_id, report_id)
);

CREATE INDEX IF NOT EXISTS idx_membership_report_usage_period
    ON membership_report_usage (membership_id, billing_period_start, created_at);
CREATE INDEX IF NOT EXISTS idx_membership_report_usage_property
    ON membership_report_usage (property_key);

COMMIT;

-- ============================================================================
-- End migration 013
-- ============================================================================
